#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

carpentry: 'incubator'

carpentry_description: 'A Carpentries Incubator lesson about combining Python and Rust'

# Overall title for pages.
title: 'From Python to Rust and Back Again'

# Date the lesson was created (YYYY-MM-DD, this is empty by default)
created: 2026-09-20

# Comma-separated list of keywords for the lesson
keywords: 'Python, Rust, PyO3, Maturin, Pixi, acorn-py, ACORN, extension modules, interoperability, performance, The Carpentries'

# Life cycle stage of the lesson
# refer to <https://docs.carpentries.org/resources/curriculum/lesson-life-cycle.html> for details
# possible values: pre-alpha, alpha, beta, stable, retired
life_cycle: 'pre-alpha'

# License of the lesson
license: 'CC-BY 4.0'

# Link to the source repository for this lesson
source: 'https://github.com/ornl-training/python-to-rust-and-back-again'

# Default branch of your lesson
branch: 'main'

# Who to contact if there are any issues
contact: 'wohlgemuthjh@ornl.gov'

# Navigation ------------------------------------------------
#
# Use the following menu items to specify the order of
# individual pages in each dropdown section. Leave blank to
# include all pages in the folder.
#
# Example -------------
#
# episodes:
# - introduction.md
# - first-steps.md
#
# learners:
# - setup.md
#
# instructors:
# - instructor-notes.md
#
# profiles:
# - one-learner.md
# - another-learner.md

# Order of episodes in your lesson
episodes:
- 01-there-and-back-again.md
- 02-translating-python-into-rust.md
- 03-where-the-analogy-ends.md
- 04-adding-rust-incrementally.md
- 05-building-with-pyo3.md
- 06-crossing-the-boundary.md
- 07-practical-guidance.md

# Information for Learners
learners:
- setup.md
- reference.md

# Information for Instructors
instructors:
- instructor-notes.md

# Learner Profiles
profiles:
- python-developer.md

# Customisation ---------------------------------------------
#
# This space below is where custom yaml items (e.g. pinning
# sandpaper and varnish versions) should live
